---
language: rust
dist: xenial
os: linux

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - bash <(travis_retry curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell) download

install:
  - gem install mdl

script:
  - make
  - make check
  - make format
  # Check that make format was executed before submitting.
  - git diff --exit-code
  # Check that hs-toxcore was updated.
  - git clone --depth=1 https://github.com/TokTok/hs-toxcore ../hs-toxcore
  - (cd ../hs-toxcore && make doc)
  - git diff --exit-code
